name: Build and Push Docker Image of Arecanut-Database

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_UNAME }}
          password: ${{ secrets.DOCKER_PSWD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Get current date in IST
        id: get_date
        run: |
          IST_DATE=$(TZ='Asia/Kolkata' date +'%Y-%m-%d')  # Format: YYYY-MM-DD
          echo "Date in IST: $IST_DATE"
          echo "::set-output name=date::$IST_DATE"

      - name: Create Dockerfile
        run: |
          echo "FROM postgres:latest" > Dockerfile
          echo "COPY ./Arecanut_complete_DB.sql /docker-entrypoint-initdb.d/" >> Dockerfile
          echo "EXPOSE 5432" >> Dockerfile

      - name: Build Docker image
        run: |
          IMAGE_TAG="${{ secrets.DOCKER_UNAME }}/pgdatabase:${{ steps.get_date.outputs.date }}"
          LATEST_TAG="${{ secrets.DOCKER_UNAME }}/pgdatabase:latest"
          
          echo "Building image with tags: $IMAGE_TAG and $LATEST_TAG"
          docker build -t $IMAGE_TAG -t $LATEST_TAG -f Dockerfile .

      - name: Push Docker image to Docker Hub
        run: |
          IMAGE_TAG="${{ secrets.DOCKER_UNAME }}/pgdatabase:${{ steps.get_date.outputs.date }}"
          LATEST_TAG="${{ secrets.DOCKER_UNAME }}/pgdatabase:latest"
          
          echo "Pushing image with tag: $IMAGE_TAG"
          docker push $IMAGE_TAG
          
          echo "Pushing image with tag: $LATEST_TAG"
          docker push $LATEST_TAG
